#!/usr/bin/env bash
#
# Deploys ansible machine

#-
#  Main
#-

set -euo pipefail

# Prompt sudo so we don't have to ask-become-pass
sudo -v

# Run Ansible with or without TTY wrapper for Darwin
if [[ "$(uname -s)" == "Darwin" ]]; then
  echo "Running on macOS – using script to preserve sudo TTY"
  script -q /dev/null ansible-playbook -i ./hosts local-dev-env.yml "$@"
else
  echo "Running on Linux"
  ansible-playbook -i ./hosts local-dev-env.yml "$@"
fi
