# vim: filetype=yaml.ansible

- name: Set up local development environment
  hosts: local
  roles:
    # Pre-reqs
    - {role: system, tags: ['system', 'bootstrap']}
    - {role: shell, tags: ['shell', 'bootstrap']}
    - {role: git, tags: ['git', 'bootstrap']}
    - {role: homebrew, tags: ['homebrew', 'bootstrap']}
    - {role: node, tags: ['node', 'bootstrap']}
    - {role: python, tags: ['python', 'bootstrap']}
    - {role: rust, tags: ['rust', 'bootstrap']}
    - {role: fonts, tags: ['fonts', 'bootstrap']}
    # Apps
    - {role: alacritty, tags: ['alacritty']}
    - {role: ansible-lint, tags: ['ansible-lint']}
    - {role: ansible-ls, tags: ['ansible-ls']}
    - {role: atool, tags: ['atool']}
    - {role: bash-ls, tags: ['bash-ls']}
    - {role: bat, tags: ['bat']}
    - {role: bitwise, tags: ['bitwise']}
    - {role: black, tags: ['black']}
    - {role: calc, tags: ['calc']}
    - {role: cheat, tags: ['cheat']}
    - {role: clang-format, tags: ['clang-format']}
    - {role: clang-format, tags: ['clangd-ls']}
    - {role: cpplint, tags: ['cpplint']}
    - {role: delta, tags: ['delta']}
    - {role: elinks, tags: ['elinks']}
    - {role: eza, tags: ['eza']}
    - {role: fd, tags: ['fd']}
    - {role: fzf, tags: ['fzf']}
    - {role: github, tags: ['github']}
    - {role: htop, tags: ['htop']}
    - {role: json-ls, tags: ['json-ls']}
    - {role: lazygit, tags: ['lazygit']}
    - {role: lua-ls, tags: ['lua-ls']}
    - {role: marksman-ls, tags: ['marksman-ls']}
    - {role: neovim, tags: ['neovim']}
    - {role: prettierd, tags: ['prettierd']}
    - {role: pyright, tags: ['pyright']}
    - {role: ripgrep, tags: ['ripgrep']}
    - {role: rsync, tags: ['rsync']}
    - {role: scroll-reverser, tags: ['scroll-reverser']}
    - {role: shellcheck, tags: ['shellcheck']}
    - {role: shfmt, tags: ['shfmt']}
    - {role: stylua, tags: ['stylua']}
    - {role: tig, tags: ['tig']}
    - {role: tinty, tags: ['tinty']}
    - {role: tmux, tags: ['tmux']}
    - {role: trash, tags: ['trash']}
    - {role: unison, tags: ['unison']}
    - {role: yaml-ls, tags: ['yaml-ls']}
    - {role: zellij, tags: ['zellij']}
    - {role: zoxide, tags: ['zoxide']}
