# vim: filetype=yaml.ansible

- name: Install delta (Linux)
  tags: [pkgs]
  become: true
  quera.github.install_from_github:
    repo: dandavison/delta
    tag: latest
    asset_regex: delta.*(?<!musl)\.tar\.gz
    version_command: delta --version
    move_rules:
      - src_regex: delta-.*/delta
        dst: "/usr/local/bin/delta"
  when: ansible_facts['system'] == "Linux"

- name: Install delta for git (MacOS)
  tags: [pkgs]
  community.general.homebrew:
    name: git-delta
    state: present
  when: ansible_facts['system'] == "Darwin"

- name: Install delta dotfiles
  tags: [dots, delta-dots]
  link_dotfiles:
    src_dir: "{{ role_path }}/dots"
