# vim: filetype=yaml.ansible

- name: Install lazygit (Linux)
  tags: [pkgs]
  become: true
  quera.github.install_from_github:
    repo: jesseduffield/lazygit
    tag: latest
    asset_regex: lazygit_.*\.tar\.gz
    version_command: lazygit --version
    move_rules:
      - src_regex: lazygit
        dst: "/usr/local/bin/lazygit"
  when: ansible_facts['system'] == "Linux"

- name: Install lazygit (MacOS)
  tags: [pkgs]
  community.general.homebrew:
    name: lazygit
    state: present
  when: ansible_facts['system'] == "Darwin"

- name: Install lazygit dotfiles
  tags: [dots, lazygit-dots]
  link_dotfiles:
    src_dir: "{{ role_path }}/dots"
