# vim: filetype=yaml.ansible

- name: Install github cli
  tags: [pkgs]
  community.general.homebrew:
    name: gh
    state: present

#- name: Get GitHub CLI extension list
#  tags: [pkgs]
#  ansible.builtin.command: gh extension list
#  register: gh_extension_list
#  changed_when: false
#  failed_when: false
#
#- name: Install github dash
#  tags: [pkgs]
#  when: '"dlvhdr/gh-dash" not in gh_extension_list.stdout'
#  ansible.builtin.command: gh extension install dlvhdr/gh-dash
#  register: dash_install_result
#  changed_when: dash_install_result.rc == 0
