# vim: filetype=yaml.ansible

- name: Install clang-format formatter (Linux)
  become: true
  tags: [pkgs]
  ansible.builtin.package:
    name:
      - clang-format
    state: present
  when: ansible_facts['system'] == "Linux"

- name: Install Clang Formatter (MacOS)
  tags: [pkgs]
  community.general.homebrew:
    name: clang-format
    state: present
  when: ansible_facts['system'] == "Darwin"
