# vim: filetype=yaml.ansible

- name: Install shfmt (Linux)
  become: true
  tags: [pkgs]
  ansible.builtin.package:
    name:
      - shfmt
    state: present
  when: ansible_facts['system'] == "Linux"

- name: Install Shfmt (MacOS)
  tags: [pkgs]
  community.general.homebrew:
    name: shfmt
    state: present
  when: ansible_facts['system'] == "Darwin"
