# vim: filetype=yaml.ansible

- name: Update/upgrade apt package manager
  ansible.builtin.import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Clean up home
  tags: [clean]
  vars:
    remove_list:
      - "{{ ansible_env.HOME }}/.lesshst"
      - "{{ ansible_env.HOME }}/.lesskey"
      - "{{ ansible_env.HOME }}/.viminfo"
      - "{{ ansible_env.HOME }}/.tig_history"
      - "{{ ansible_env.HOME }}/.calc_history"
      - "{{ ansible_env.HOME }}/.zcompdump"
  block:
    - name: Remove unwanted dotfiles
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop: "{{ remove_list }}"

- name: Clean dead symlinks in $HOME
  tags: [clean]
  ansible.builtin.shell:
    cmd: |
      find {{ ansible_env.HOME }} -maxdepth 1 -type l ! -exec test -e {} \; -exec rm {} \;
    executable: /bin/bash
  changed_when: false

- name: Clean dead symlinks in XDG_DIRS recursively
  tags: [clean]
  ansible.builtin.shell:
    cmd: |
      if [ -d "{{ item }}" ]; then
        find "{{ item }}" -type l ! -exec test -e {} \; -exec rm -f {} \;
      fi
    executable: /bin/bash
  changed_when: false
  loop:
    - "{{ ansible_env.HOME }}/.config"
    - "{{ ansible_env.HOME }}/.local"
    - "{{ ansible_env.HOME }}/.cache"

- name: Ensure required directories
  become: true
  ensure_dirs:
    dirs:
      - path: /usr/local/share/man/man1
      - path: /usr/local/share/man/man5
      - path: /usr/local/share/man/man8
