# vim: filetype=yaml.ansible

- name: Install prettierd formatter (Linux)
  become: true
  tags: [pkgs, prettierd]
  community.general.npm:
    name: "@fsouza/prettierd"
    global: true
    state: present
  when: ansible_facts['system'] == "Linux"

- name: Install Prettierd (MacOS)
  tags: [pkgs]
  community.general.homebrew:
    name: prettierd
    state: present
  when: ansible_facts['system'] == "Darwin"
