# vim: filetype=yaml.ansible

- name: Install bash language server (Linux)
  become: true
  tags: [pkgs]
  community.general.npm:
    name: "bash-language-server"
    global: true
    state: present
  when: ansible_facts['system'] == "Linux"

- name: Install Bash Language Server (MacOS)
  tags: [pkgs]
  community.general.homebrew:
    name: bash-language-server
    state: present
  when: ansible_facts['system'] == "Darwin"
