# vim: filetype=yaml.ansible

- name: Install fzf
  tags: [pkgs]
  become: true
  quera.github.install_from_github:
    repo: junegunn/fzf
    tag: latest
    asset_regex: fzf-.*\.tar\.gz
    version_command: fzf --version
    move_rules:
      - src_regex: fzf
        dst: "/usr/local/bin/fzf"
  when: ansible_facts['system'] == "Linux"

- name: Install fzf
  tags: [pkgs]
  community.general.homebrew:
    name: fzf
    state: present
  when: ansible_facts['system'] == "Darwin"

- name: Install fzf dotfiles
  tags: [dots, fzf-dots]
  link_dotfiles:
    src_dir: "{{ role_path }}/dots"
