# vim: filetype=yaml.ansible

- name: Install bitwise (Linux)
  become: true
  tags: [pkgs]
  ansible.builtin.package:
    name:
      - bitwise
    state: present
  when: ansible_facts['system'] == "Linux"

- name: Install bitwise (MacOS)
  tags: [pkgs]
  community.general.homebrew:
    name: bitwise
    state: present
  when: ansible_facts['system'] == "Darwin"
