# vim: filetype=yaml.ansible

- name: Install clangd language server (Linux)
  become: true
  tags: [pkgs]
  ansible.builtin.package:
    name:
      - clangd
    state: present
  when: ansible_facts['system'] == "Linux"

- name: Install llvm (MacOS)
  tags: [pkgs]
  community.general.homebrew:
    name: llvm
    state: present
  when: ansible_facts['system'] == "Darwin"
