# vim: filetype=yaml.ansible

- name: Install ansible language server (Linux)
  become: true
  tags: [pkgs]
  community.general.npm:
    name: "@ansible/ansible-language-server"
    global: true
    state: present
  when: ansible_facts['system'] == "Linux"

- name: Install Ansible Language Server (MacOS)
  tags: [pkgs]
  community.general.homebrew:
    name: ansible-language-server
    state: present
  when: ansible_facts['system'] == "Darwin"
