# vim: filetype=yaml.ansible

- name: Install ansible-lint for ansible-ls (Linux)
  tags: [pkgs]
  community.general.pipx:
    name: ansible-lint
    state: present
  when: ansible_facts['system'] == "Linux"

- name: Install Ansible Linter (MacOS)
  tags: [pkgs]
  community.general.homebrew:
    name: ansible-lint
    state: present
  when: ansible_facts['system'] == "Darwin"
