# vim: filetype=yaml.ansible

- name: Install Stylua
  tags: [pkgs]
  community.general.homebrew:
    name: stylua
    state: present

- name: Install stylua dotfiles
  tags: [dots]
  link_dotfiles:
    src_dir: "{{ role_path }}/dots"
