# vim: filetype=yaml.ansible

- name: Install bat (Linux)
  tags: [pkgs]
  become: true
  quera.github.install_from_github:
    repo: sharkdp/bat
    tag: latest
    asset_regex: bat-.*(?<!musl)\.tar\.gz
    version_command: bat --version
    move_rules:
      - src_regex: bat-.*/bat
        dst: "/usr/local/bin"
      - src_regex: bat-.*/autocomplete/bat.bash
        dst: "/usr/share/bash-completion/completions/bat"
      - src_regex: bat-.*/autocomplete/bat.zsh
        dst: "/usr/local/share/zsh/site-functions/_bat"
  when: ansible_facts['system'] == "Linux"

- name: Install bat (MacOS)
  tags: [pkgs]
  community.general.homebrew:
    name: bat
    state: present
  when: ansible_facts['system'] == "Darwin"

- name: Install bat dotfiles
  tags: [dots, bat-dots]
  link_dotfiles:
    src_dir: "{{ role_path }}/dots"
