# vim: filetype=yaml.ansible

- name: Install zellij (Linux)
  tags: [pkgs]
  become: true
  quera.github.install_from_github:
    repo: zellij-org/zellij
    tag: latest
    asset_regex: zellij-.*\.tar\.gz
    version_command: zellij --version
    move_rules:
      - src_regex: zellij
        dst: "/usr/local/bin/zellij"
  when: ansible_facts['system'] == "Linux"

- name: Install zellij (MacOS)
  tags: [pkgs]
  community.general.homebrew:
    name: zellij
    state: present
  when: ansible_facts['system'] == "Darwin"

- name: Install zellij dotfiles
  tags: [dots, zellij-dots]
  link_dotfiles:
    src_dir: "{{ role_path }}/dots"
